httpListenAddress: :8080
checkInterval: 10s
storage:
  type: etcd
  config:
    endpoints:
      - localhost:2379
services:
  - id: srv1
    timeout: 60s
    webhooks:
      - method: GET
        url: https://doesntexist.foo
  - id: srv2
    timeout: 30s
    webhooks:
      - method: GET
        url: https://alsodoesntexist.foo
