listen: :8080
checkInterval: 10s
username: admin
password: admin
storage:
  type: memory
services:
  - id: example-service
    timeout: 30s
    debounce: 1m
    alertNotifications:
      - type: slack
        config:
          token: xoxb-xxxxxxxxxxx-xxxxxxxxxxxxxx-xxxxxxxxxxxxxxxxx
          channel: testing
          messageFields:
            - key: environment
              value: dev
            - key: customer
              value: somecorp
